spring:
  application:
    name:apiUsuarios
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
    h2:
      console:
        enabled: 'true'
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      
springdoc:
  swagger-ui:
    path: /swagger-ui.html


# App Properties
api:
  app:
    tokenjwt: secret
    tokenjwtexpirate: 86400000

server:  
  servlet:
    context-path: /api


